Kotlin. Homework #2. Task #1
Belgrak/shallowSizeTemplate pull request #1
Opened 2022-03-23 06:08 UTC by Belgrak

2022-03-27 14:16 UTC, illided requested changes

2022-03-27 14:16 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                            |   fun shallowSize(): Int = 0
Давай здесь сделаем что то более радикальное, например кинуть ошибку что замена не произошла

2022-03-28 09:01 UTC, illided requested changes

2022-03-28 09:01 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                            |       throw NoSuchMethodException("shallowSize function not implemented")
Мне кажется здесь лучше другое исключение кинуть, типо `IllegalStateException` или `NotImplementedError`

2022-03-28 09:01 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    for (element in clazz.properties) {
Это можно по котлиновски по простому сделать)

2022-03-28 09:01 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                            |   fun shallowSize(): Int {
Давай название функции тоже выведем в константу, чтобы не изменять его потом ручками в случае рефакторинга

2022-03-28 09:01 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    clazz.functions.find { it.name.toString() == "shallowSize" && it.valueParameters.isEmpty() }
Лучше сделать функцию `isShallowSizeFunction()`

2022-03-28 09:01 UTC, illided commented on .github/workflows/main.yml
> +        run: ./gradlew detekt
Меня попросили вас тыркать за дефолтный конфиг)
Добавь что нибудь интересное, типо [тест репортов](https://github.com/actions/upload-artifact)

2022-04-13 15:38 UTC, illided approved these changes
Атлишна. Перекидываю тебя на Настю

2022-04-13 15:39 UTC, illided commented
А, ты ее в колабораторы не добавил. Добавь тогда пожалуйста и кинь если не сложно)

2022-04-19 07:40 UTC, nbirillo approved these changes

2022-04-19 07:40 UTC, merged